package acp.acp_project.Models;

public enum SpecificActions {
    FIND_AND_REPLACE,
    MERGE,
    CONVERT_TO_WORD,
    CONVERT_TO_EXCEL,
    CONVERT_TO_PDF,
    CONVERT_TO_TEXT,
    CONVERT_TO_CSV,
    CONVERT_TO_JSON,
    REMOVE_DUPLICATES,
    WATERMARK,
    SEARCH_BY_KEYWORD,
    EXTRACT_FILES,
    CONVERT_TO_PNG,
    CONVERT_TO_JPEG,
    CONVERT_TO_JPG,
    REDUCE_IMAGE_SIZE,
    REDUCE_VIDEO_SIZE,
    EXTRACT_AUDIO,
    PRINT
}
